apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
        environment: production        
    spec:
      containers:
      - name: book
        image: dilshannaveen/sample-exercise:book-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: book
spec:
  type: ClusterIP
  selector:
    app: book
  ports:
  - port: 8080 # for the example of customer EX:3 => I setup this port to 80 from 8081
    targetPort: 8080
